"use strict";

systemDictionary = {
    "Add On/Off schedule": {
        en: "Add On/Off schedule",
        de: "An/Aus Schaltplan hinzufügen",
        ru: "Добавить вкл / выкл расписание",
        pt: "Adicionar programação On / Off",
        nl: "Aan / uit-schema toevoegen",
        fr: "Ajouter un programme On / Off",
        it: "Aggiungi pianificazione On / Off",
        es: "Agregar horario de encendido / apagado",
        pl: "Dodaj harmonogram włączania / wyłączania",
        uk: "Графік роботи",
        "zh-cn": "添加开/关时间表",
    },
    Friday: {
        en: "Friday",
        de: "Freitag",
        ru: "пятница",
        pt: "Sexta-feira",
        nl: "vrijdag",
        fr: "Vendredi",
        it: "Venerdì",
        es: "viernes",
        pl: "piątek",
        uk: "П'ятниця",
        "zh-cn": "星期五",
    },
    Monday: {
        en: "Monday",
        de: "Montag",
        ru: "понедельник",
        pt: "Segunda-feira",
        nl: "maandag",
        fr: "Lundi",
        it: "Lunedi",
        es: "lunes",
        pl: "poniedziałek",
        uk: "понеділок",
        "zh-cn": "星期一",
    },
    Saturday: {
        en: "Saturday",
        de: "Samstag",
        ru: "суббота",
        pt: "sábado",
        nl: "zaterdag",
        fr: "samedi",
        it: "Sabato",
        es: "sábado",
        pl: "sobota",
        uk: "Субота",
        "zh-cn": "星期六",
    },
    Sunday: {
        en: "Sunday",
        de: "Sonntag",
        ru: "Воскресенье",
        pt: "domingo",
        nl: "zondag",
        fr: "dimanche",
        it: "Domenica",
        es: "domingo",
        pl: "niedziela",
        uk: "неділя",
        "zh-cn": "星期日",
    },
    Thursday: {
        en: "Thursday",
        de: "Donnerstag",
        ru: "Четверг",
        pt: "Quinta-feira",
        nl: "donderdag",
        fr: "Jeudi",
        it: "giovedi",
        es: "jueves",
        pl: "czwartek",
        uk: "четвер",
        "zh-cn": "星期四",
    },
    Tuesday: {
        en: "Tuesday",
        de: "Dienstag",
        ru: "вторник",
        pt: "terça",
        nl: "dinsdag",
        fr: "Mardi",
        it: "martedì",
        es: "martes",
        pl: "wtorek",
        uk: "вівторок",
        "zh-cn": "星期二",
    },
    Wednesday: {
        en: "Wednesday",
        de: "Mittwoch",
        ru: "среда",
        pt: "Quarta-feira",
        nl: "woensdag",
        fr: "Mercredi",
        it: "mercoledì",
        es: "miércoles",
        pl: "środa",
        uk: "Середа",
        "zh-cn": "星期三",
    },
    addAstroTrigger: {
        en: "Astro trigger",
        de: "Astro Trigger",
        ru: "Астро триггер",
        pt: "Astro trigger",
        nl: "Astro-trigger",
        fr: "Déclenchement astro",
        it: "Astro trigger",
        es: "Astro gatillo",
        pl: "Spust Astro",
        uk: "Астро тригер",
        "zh-cn": "天文触发器",
    },
    addCondition: {
        en: "Add condition",
        de: "Bedingung hinzufügen",
        ru: "Добавить условие",
        pt: "Adicionar condição",
        nl: "Voorwaarde toevoegen",
        fr: "Ajouter une condition",
        it: "Aggiungi condizione",
        es: "Agregar condición",
        pl: "Dodaj warunek",
        uk: "Додайте умову",
        "zh-cn": "添加条件",
    },
    addTimeTrigger: {
        en: "Time trigger",
        de: "Time trigger",
        ru: "Время запуска",
        pt: "Gatilho de tempo",
        nl: "Tijd trigger",
        fr: "Déclencheur temporel",
        it: "Innesco temporale",
        es: "Disparador de tiempo",
        pl: "Wyzwalacz czasowy",
        uk: "Тригер часу",
        "zh-cn": "时间触发",
    },
    addTrigger: {
        en: "Add trigger",
        de: "Auslöser hinzufügen",
        ru: "Добавить триггер",
        pt: "Adicionar gatilho",
        nl: "Trigger toevoegen",
        fr: "Ajouter un déclencheur",
        it: "Aggiungi trigger",
        es: "Agregar disparador",
        pl: "Dodaj wyzwalacz",
        uk: "Додати тригер",
        "zh-cn": "添加触发器",
    },
    allOff: {
        en: "All off",
        de: "Alle aus",
        ru: "Все выключить",
        pt: "Tudo desligado",
        nl: "Allemaal uit",
        fr: "Tout éteint",
        it: "Tutto fuori",
        es: "Todo apagado",
        pl: "Wszystko wyłączone",
        uk: "Все вимкнено",
        "zh-cn": "全部关闭",
    },
    allOn: {
        en: "All on",
        de: "Alle an",
        ru: "Все на",
        pt: "Tudo em cima",
        nl: "Allemaal aan",
        fr: "Tout sur",
        it: "Tutto acceso",
        es: "Todo en",
        pl: "Wszystko włączone",
        uk: "Все включено",
        "zh-cn": "所有",
    },
    automaticSwitchingEnabled: {
        en: "Automatic switching enabled",
        de: "Automatisches Schalten aktiviert",
        ru: "Автоматическое переключение включено",
        pt: "Comutação automática ativada",
        nl: "Automatisch schakelen ingeschakeld",
        fr: "Commutation automatique activée",
        it: "Commutazione automatica abilitata",
        es: "Conmutación automática habilitada",
        pl: "Automatyczne przełączanie włączone",
        uk: "Увімкнено автоматичне перемикання",
        "zh-cn": "启用自动切换",
    },
    boolean: {
        en: "boolean",
        de: "Wahrheitswert",
        ru: "логический",
        pt: "boleano",
        nl: "boolean",
        fr: "booléen",
        it: "booleano",
        es: "booleano",
        pl: "boolean",
        uk: "логічний",
        "zh-cn": "布尔值",
    },
    cancelEdit: {
        en: "Cancel edit",
        de: "Bearbeiten abbrechen",
        ru: "Отменить редактирование",
        pt: "Cancelar edição",
        nl: "Bewerken annuleren",
        fr: "Annuler la modification",
        it: "Annulla modifica",
        es: "Cancelar edición",
        pl: "Anuluj edycję",
        uk: "Скасувати редагування",
        "zh-cn": "取消编辑",
    },
    condition: {
        en: "Condition",
        de: "Bedingung",
        ru: "Состояние",
        pt: "Doença",
        nl: "Staat",
        fr: "État",
        it: "Condizione",
        es: "Condición",
        pl: "Stan: schorzenie",
        uk: "Хвороба",
        "zh-cn": "健康）状况",
    },
    conditionStateAlias: {
        en: "Condition state alias",
        de: "Bedingung State Alias",
        ru: "Псевдоним состояния состояния",
        pt: "Alias ​​de estado de condição",
        nl: "Staat alias",
        fr: "Alias ​​d'état de condition",
        it: "Alias ​​di stato della condizione",
        es: "Alias ​​de estado de condición",
        pl: "Alias ​​stanu warunku",
        uk: "Псевдонім стану стану",
        "zh-cn": "条件状态别名",
    },
    conditionStateId: {
        en: "Condition state id",
        de: "Bedingung State Id",
        ru: "Идентификатор состояния состояния",
        pt: "ID de estado de condição",
        nl: "Conditie staat id",
        fr: "ID de l'état de la condition",
        it: "ID stato condizione",
        es: "Id. De estado de condición",
        pl: "Identyfikator stanu warunku",
        uk: "Ідентифікатор стану стану",
        "zh-cn": "条件状态编号",
    },
    oid: {
        en: "Condition state id (VIS-2 only)",
        de: "Bedingung State Id (nur VIS-2)",
        ru: "Состояние состояния id (только ВИС-2)",
        pt: "Estado de condição id (apenas VIS-2)",
        nl: "Status-ID (alleen VIS-2)",
        fr: "État id (VIS-2 seulement)",
        it: "Stato di condizione id (solo VIS-2)",
        es: "Estado de condición id (sólo VIS-2)",
        pl: "Stan stanu warunku id (tylko VIS-2)",
        uk: "Ідентифікатор стану стану (лише VIS-2)",
        "zh-cn": "条件状态 id(只有VIS-2)",
    },
    conditionStatesCount: {
        en: "Count of condition states",
        de: "Anzahl State für Bedingungen",
        ru: "Количество состояний состояния",
        pt: "Contagem de estados de condição",
        nl: "Aantal condities",
        fr: "Nombre d'états de condition",
        it: "Conteggio degli stati di condizione",
        es: "Recuento de estados de condición",
        pl: "Liczba stanów warunkowych",
        uk: "Підрахунок умовних станів",
        "zh-cn": "条件状态计数",
    },
    currentValue: {
        en: "Current value",
        de: "Aktueller Wert",
        ru: "Текущая стоимость",
        pt: "Valor atual",
        nl: "Huidige waarde",
        fr: "Valeur actuelle",
        it: "Valore corrente",
        es: "Valor actual",
        pl: "Aktualna wartość",
        uk: "Поточне значення",
        "zh-cn": "当前值",
    },
    dataId: {
        en: "Schedule data id",
        de: "Id für Schaltplandaten",
        ru: "Расписание данных ID",
        pt: "ID de dados da programação",
        nl: "Plan gegevens-ID",
        fr: "Planifier l'identifiant des données",
        it: "Pianifica ID dati",
        es: "Programar ID de datos",
        pl: "Zaplanuj identyfikator danych",
        uk: "Ідентифікатор даних розкладу",
        "zh-cn": "时间表资料编号",
    },
    oid6: {
        en: "Schedule data id (VIS-2 only)",
        de: "Id für Schaltplandaten (nur VIS-2)",
        ru: "Расписание данных ID (только VIS-2)",
        pt: "ID de dados da programação (apenas VIS-2)",
        nl: "Plan gegevens-ID (alleen VIS-2)",
        fr: "Planifier l'identifiant des données (VIS-2 seulement)",
        it: "Pianifica ID dati (solo VIS-2)",
        es: "Programar ID de datos (sólo VIS-2)",
        pl: "Zaplanuj identyfikator danych (tylko VIS-2)",
        uk: "Ідентифікатор даних розкладу (лише VIS-2)",
        "zh-cn": "时间表资料编号(仅限VIS-2)",
    },
    oid8: {
        en: "Schedule enable id (VIS-2 only)",
        de: "Zeitplan aktivieren id (nur VIS-2)",
        ru: "Расписание id (только VIS-2)",
        pt: "Programação ativar id (apenas VIS-2)",
        nl: "Schema id inschakelen (alleen VIS-2)",
        fr: "Indicatif du calendrier (VIS-2 seulement)",
        it: "Programma abilitare id (solo VIS-2)",
        es: "Horario de habilitación id (sólo VIS-2)",
        pl: "Harmonogram włącza id (tylko VIS-2)",
        uk: "Ідентифікатор увімкнення розкладу (лише VIS-2)",
        "zh-cn": "时刻表启用 ID(仅限VIS-2)",
    },
    editName: {
        en: "Edit name",
        de: "Namen bearbeiten",
        ru: "Редактировать название",
        pt: "Editar nome",
        nl: "Naam bewerken",
        fr: "Modifier le nom",
        it: "Modifica nome",
        es: "Editar nombre",
        pl: "Zmień imię",
        uk: "Редагувати назву",
        "zh-cn": "编辑名称",
    },
    editTrigger: {
        en: "Edit trigger",
        de: "Auslöser bearbeiten",
        ru: "Редактировать триггер",
        pt: "Editar gatilho",
        nl: "Trigger bewerken",
        fr: "Modifier le déclencheur",
        it: "Modifica trigger",
        es: "Editar disparador",
        pl: "Edytuj wyzwalacz",
        uk: "Редагувати тригер",
        "zh-cn": "编辑触发器",
    },
    enabled: {
        en: "Enabled",
        de: "Aktiv",
        ru: "Включено",
        pt: "ativado",
        nl: "Ingeschakeld",
        fr: "Activée",
        it: "Abilitato",
        es: "Habilitado",
        pl: "Włączone",
        uk: "Увімкнено",
        "zh-cn": "已启用",
    },
    equals: {
        en: "Equals",
        de: "Gleich",
        ru: "Равно",
        pt: "É igual a",
        nl: "Gelijk aan",
        fr: "Équivaut à",
        it: "È uguale a",
        es: "Igual",
        pl: "Równa się",
        uk: "Дорівнює",
        "zh-cn": "等于",
    },
    equalsNot: {
        en: "Equals not",
        de: "Ungleich",
        ru: "Равно не",
        pt: "Não é igual",
        nl: "Is gelijk aan niet",
        fr: "Égale non",
        it: "Non è uguale",
        es: "Es igual a no",
        pl: "Nie równa się",
        uk: "Не дорівнює",
        "zh-cn": "不等于",
    },
    false: {
        en: "false",
        de: "nein",
        ru: "ложный",
        pt: "falso",
        nl: "false",
        fr: "faux",
        it: "falso",
        es: "falso",
        pl: "fałszywe",
        uk: "помилковий",
        "zh-cn": "假",
    },
    inputAstroTime: {
        en: "Astro time: ",
        de: "Astrozeit:",
        ru: "Астро время:",
        pt: "Tempo Astro:",
        nl: "Astrotijd:",
        fr: "Heure Astro:",
        it: "Tempo di Astro:",
        es: "Tiempo astro:",
        pl: "Czas Astro:",
        uk: "Астрочас:",
        "zh-cn": "太空时间：",
    },
    inputShiftInMinutes: {
        en: "Shift in minutes:",
        de: "Verschoben um (in Minuten):",
        ru: "Сдвиг в минутах:",
        pt: "Mudança em minutos:",
        nl: "Verschuiving in minuten:",
        fr: "Décalage en minutes:",
        it: "Spostamento in pochi minuti:",
        es: "Turno en minutos:",
        pl: "Zmiana w minutach:",
        uk: "Зміна за хвилини:",
        "zh-cn": "上班时间：",
    },
    manualSwitching: {
        en: "Manual switching",
        de: "Manuelles Schalten",
        ru: "Ручное переключение",
        pt: "Comutação manual",
        nl: "Handmatig schakelen",
        fr: "Commutation manuelle",
        it: "Commutazione manuale",
        es: "Cambio manual",
        pl: "Przełączanie ręczne",
        uk: "Ручне перемикання",
        "zh-cn": "手动切换",
    },
    name: {
        en: "Name",
        de: "Name",
        ru: "имя",
        pt: "Nome",
        nl: "Naam",
        fr: "Nom",
        it: "Nome",
        es: "Nombre",
        pl: "Imię",
        uk: "Ім'я",
        "zh-cn": "名称",
    },
    needToEnterValidNumberOff: {
        en: "Enter a valid number for switched off value when type is number!",
        de: "Geben Sie eine gültige Zahl als Aus-Wert ein, wenn Typ Zahl ist!",
        ru: "Введите действительное число для выключенного значения, когда тип является числом!",
        pt: "Digite um número válido para o valor desativado quando o tipo for número!",
        nl: "Voer een geldig nummer in voor uitgeschakelde waarde als type nummer is!",
        fr: "Entrez un nombre valide pour la valeur désactivée lorsque le type est un nombre!",
        it: "Inserisci un numero valido per il valore disattivato quando type è number!",
        es: "¡Ingrese un número válido para el valor apagado cuando type es number!",
        pl: "Wprowadź poprawny numer wyłączonej wartości, gdy typ jest liczbą!",
        uk: "Введіть дійсне число для вимкненого значення, якщо типом є число!",
        "zh-cn": "输入数字时，输入一个有效的数字作为关闭值！",
    },
    needToEnterValidNumberOn: {
        en: "Enter a valid number for switched on value when type is number!",
        de: "Geben Sie eine gültige Zahl für den An-Wert ein, wenn Typ Zahl ist!",
        ru: "Введите действительное число для включенного значения, когда тип является числом!",
        pt: "Digite um número válido para o valor ativado quando o tipo for número!",
        nl: "Voer een geldig nummer in voor ingeschakelde waarde wanneer type nummer is!",
        fr: "Entrez un nombre valide pour la valeur activée lorsque le type est un nombre!",
        it: "Inserisci un numero valido per il valore attivato quando type è number!",
        es: "¡Ingrese un número válido para el valor activado cuando type es number!",
        pl: "Wprowadź prawidłową liczbę dla włączonej wartości, gdy typ jest liczbą!",
        uk: "Введіть дійсне число для ввімкненого значення, якщо типом є число!",
        "zh-cn": "当类型为数字时，输入有效的数字作为接通值！",
    },
    needToEnterValidStringValue: {
        en: "On/Offvalue cannot be empty when type is string!",
        de: "Ein-/Aus-Wert darf nicht leer sein, wenn der Typ Zeichenfolge ist!",
        ru: "Значение On / Offval не может быть пустым, когда тип является строкой",
        pt: "On / Offvalue não pode ficar vazio quando o tipo é string",
        nl: "Aan / Uitwaarde mag niet leeg zijn als type string is",
        fr: "La valeur On / Off ne peut pas être vide lorsque le type est une chaîne",
        it: "Il valore On / Off non può essere vuoto quando il tipo è stringa",
        es: "On / Offvalue no puede estar vacío cuando type es string",
        pl: "Wartość On / Offvalue nie może być pusta, gdy typ jest łańcuchem",
        uk: "Значення On/Off не може бути пустим, якщо типом є рядок!",
        "zh-cn": "类型为字符串时，On / Offvalue不能为空",
    },
    needToSelectDataId: {
        en: "Select a schedule data id to use the widget!",
        de: "Wählen Sie eine Schaltplandaten Id aus, um das Widget zu verwenden!",
        ru: "Выберите идентификатор данных расписания, чтобы использовать виджет!",
        pt: "Selecione um ID de dados de agendamento para usar o widget!",
        nl: "Selecteer een schema-gegevens-ID om de widget te gebruiken!",
        fr: "Sélectionnez un identifiant de données de planification pour utiliser le widget!",
        it: "Seleziona un ID dati di pianificazione per utilizzare il widget!",
        es: "¡Seleccione una identificación de datos de programación para usar el widget!",
        pl: "Wybierz identyfikator danych harmonogramu, aby użyć widgetu!",
        uk: "Виберіть ідентифікатор даних розкладу, щоб використовувати віджет!",
        "zh-cn": "选择一个计划数据ID以使用小部件！",
    },
    needToSelectStateId: {
        en: "Select at least one switched state id to use the widget!",
        de: "Wählen Sie mindestens eine geschaltete State Id aus, um das Widget zu verwenden!",
        ru: "Выберите хотя бы один идентификатор переключенного состояния, чтобы использовать виджет!",
        pt: "Selecione pelo menos um ID de estado alternado para usar o widget!",
        nl: "Selecteer ten minste één ID voor geschakelde status om de widget te gebruiken!",
        fr: "Sélectionnez au moins un identifiant d'état commuté pour utiliser le widget!",
        it: "Seleziona almeno un ID stato commutato per utilizzare il widget!",
        es: "¡Seleccione al menos un ID de estado cambiado para usar el widget!",
        pl: "Wybierz przynajmniej jeden identyfikator stanu przełączania, aby użyć widżetu!",
        uk: "Виберіть хоча б один ідентифікатор переключеного стану, щоб використовувати віджет!",
        "zh-cn": "选择至少一个切换状态ID以使用小部件！",
    },
    needToSelectValidDataId: {
        en: "Select a valid schedule data id (with pattern 'time-switch.0.onoff.*.data')!",
        de: "Wählen Sie eine gültige Schaltplandaten Id (mit dem Muster 'time-switch.0.onoff.*.data')!",
        ru: "Выберите действительный идентификатор данных расписания (с шаблоном 'time-switch.0.onoff. *. Data')!",
        pt: "Selecione um ID de dados de programação válido (com o padrão 'time-switch.0.onoff. *. Data')!",
        nl: "Selecteer een geldige data-ID voor het schema (met patroon 'time-switch.0.onoff. *. Data')!",
        fr: "Sélectionnez un identifiant de données de planification valide (avec le modèle 'time-switch.0.onoff. *. Data')!",
        it: "Selezionare un ID dati di pianificazione valido (con il modello 'time-switch.0.onoff. *. Data')!",
        es: "¡Seleccione una identificación de datos de programación válida (con el patrón 'time-switch.0.onoff. *. Data')!",
        pl: "Wybierz prawidłowy identyfikator danych harmonogramu (ze wzorcem „time-switch.0.onoff. *. Data”)!",
        uk: "Виберіть дійсний ідентифікатор даних розкладу (із шаблоном 'time-switch.0.onoff.*.data')!",
        "zh-cn": "选择一个有效的计划数据ID（使用模式“ time-switch.0.onoff。*。data”）！",
    },
    number: {
        en: "number",
        de: "Zahl",
        ru: "число",
        pt: "número",
        nl: "aantal",
        fr: "nombre",
        it: "numero",
        es: "número",
        pl: "numer",
        uk: "номер",
        "zh-cn": "数",
    },
    off: {
        en: "Off",
        de: "aus",
        ru: "от",
        pt: "Fora",
        nl: "Uit",
        fr: "De",
        it: "via",
        es: "Apagado",
        pl: "Poza",
        uk: "Вимкнено",
        "zh-cn": "关",
    },
    offValue: {
        en: "Value for off",
        de: "Wert für aus",
        ru: "Значение для выкл",
        pt: "Valor para off",
        nl: "Waarde voor uit",
        fr: "Valeur pour off",
        it: "Valore per spento",
        es: "Valor para apagado",
        pl: "Wartość wyłączona",
        uk: "Значення для викл",
        "zh-cn": "折价",
    },
    on: {
        en: "On",
        de: "an",
        ru: "На",
        pt: "Em",
        nl: "Aan",
        fr: "Sur",
        it: "Su",
        es: "En",
        pl: "Na",
        uk: "Увімкнено",
        "zh-cn": "上",
    },
    onValue: {
        en: "Value for on",
        de: "Wert für an",
        ru: "Значение для на",
        pt: "Valor para on",
        nl: "Waarde voor op",
        fr: "Valeur pour on",
        it: "Valore per on",
        es: "Valor para en",
        pl: "Wartość dla włączenia",
        uk: "Значення для на",
        "zh-cn": "的价值",
    },
    removeCondition: {
        en: "Remove condition",
        de: "Bedingung entfernen",
        ru: "Удалить условие",
        pt: "Remover condição",
        nl: "Voorwaarde verwijderen",
        fr: "Supprimer la condition",
        it: "Rimuovi condizione",
        es: "Eliminar condición",
        pl: "Usuń warunek",
        uk: "Видалити умову",
        "zh-cn": "删除条件",
    },
    removeSchedule: {
        en: "Remove schedule",
        de: "Zeitplan entfernen",
        ru: "Удалить расписание",
        pt: "Remover agendamento",
        nl: "Schema verwijderen",
        fr: "Supprimer le calendrier",
        it: "Rimuovi programma",
        es: "Eliminar horario",
        pl: "Usuń harmonogram",
        uk: "Видалити розклад",
        "zh-cn": "删除时间表",
    },
    removeTrigger: {
        en: "Remove trigger",
        de: "Auslöser entfernen",
        ru: "Удалить триггер",
        pt: "Remover gatilho",
        nl: "Trigger verwijderen",
        fr: "Supprimer la gâchette",
        it: "Rimuovi grilletto",
        es: "Eliminar gatillo",
        pl: "Usuń spust",
        uk: "Зніміть тригер",
        "zh-cn": "删除触发器",
    },
    saveChanges: {
        en: "Save changes",
        de: "Änderungen speichern",
        ru: "Сохранить изменения",
        pt: "Salvar alterações",
        nl: "Wijzigingen opslaan",
        fr: "Sauvegarder les modifications",
        it: "Salvare le modifiche",
        es: "Guardar cambios",
        pl: "Zapisz zmiany",
        uk: "Зберегти зміни",
        "zh-cn": "保存更改",
    },
    saveName: {
        en: "Save name",
        de: "Name speichern",
        ru: "Сохранить имя",
        pt: "Salvar nome",
        nl: "Naam opslaan",
        fr: "Enregistrer le nom",
        it: "Salva nome",
        es: "Guardar nombre",
        pl: "Zapisz imię",
        uk: "Зберегти назву",
        "zh-cn": "保存名字",
    },
    scheduleId: {
        en: "Schedule data id",
        de: "Schaltplandaten Id",
        ru: "Расписание данных ID",
        pt: "ID de dados da programação",
        nl: "Plan gegevens-ID",
        fr: "Planifier l'identifiant des données",
        it: "Pianifica ID dati",
        es: "Programar ID de datos",
        pl: "Zaplanuj identyfikator danych",
        uk: "Ідентифікатор даних розкладу",
        "zh-cn": "时间表资料编号",
    },
    showConditionIds: {
        en: "Show condition state ids",
        de: "Anzeigen von Bedingungs State Ids",
        ru: "Показать идентификаторы состояния условия",
        pt: "Mostrar ids de estado de condição",
        nl: "Staats-ID's weergeven",
        fr: "Afficher les identifiants d'état des conditions",
        it: "Mostra gli ID di stato della condizione",
        es: "Mostrar ID de estado de condición",
        pl: "Pokaż identyfikatory stanów warunków",
        uk: "Показати ідентифікатори станів умов",
        "zh-cn": "显示条件状态ID",
    },
    showId: {
        en: "Show switched state id",
        de: "Anzeigen des geschaltenen States",
        ru: "Показать идентификатор переключенного состояния",
        pt: "Mostrar ID do estado comutado",
        nl: "Toon geschakelde status-ID",
        fr: "Afficher l'ID de l'état commuté",
        it: "Mostra ID stato commutato",
        es: "Mostrar ID de estado cambiado",
        pl: "Pokaż identyfikator stanu przełączonego",
        uk: "Показати ідентифікатор переключеного стану",
        "zh-cn": "显示切换状态ID",
    },
    showManualSwitch: {
        en: "Show manual switch",
        de: "Anzeigen der manuellen Schalter",
        ru: "Показать ручной переключатель",
        pt: "Mostrar interruptor manual",
        nl: "Handmatige schakelaar weergeven",
        fr: "Afficher le commutateur manuel",
        it: "Mostra interruttore manuale",
        es: "Mostrar interruptor manual",
        pl: "Pokaż przełącznik ręczny",
        uk: "Показати ручний перемикач",
        "zh-cn": "显示手动开关",
    },
    solarNoon: {
        en: "Noon",
        de: "Mittag",
        ru: "Полдень",
        pt: "Meio-dia",
        nl: "Middag",
        fr: "Le midi",
        it: "Mezzogiorno",
        es: "Mediodía",
        pl: "Południe",
        uk: "полудень",
        "zh-cn": "中午",
    },
    stateId: {
        en: "Switched state id",
        de: "Id vom geschaltenen State",
        ru: "Идентификатор переключенного состояния",
        pt: "ID do estado comutado",
        nl: "Geschakelde status-ID",
        fr: "Identifiant d'état commuté",
        it: "ID stato commutato",
        es: "ID de estado conmutado",
        pl: "Identyfikator stanu przełączonego",
        uk: "Переключений ідентифікатор стану",
        "zh-cn": "切换状态编号",
    },
    oid7: {
        en: "Switched state id (VIS-2 only)",
        de: "Id vom geschaltenen State (nur VIS-2)",
        ru: "Идентификатор переключенного состояния (только VIS-2)",
        pt: "ID do estado comutado (apenas VIS-2)",
        nl: "Geschakelde status-ID (alleen VIS-2)",
        fr: "Identifiant d'état commuté (VIS-2 seulement)",
        it: "ID stato commutato (solo VIS-2)",
        es: "ID de estado conmutado ((sólo VIS-2))",
        pl: "Identyfikator stanu przełączonego (tylko VIS-2)",
        uk: "Переключений ідентифікатор стану (лише VIS-2)",
        "zh-cn": "切换状态编号(仅限VIS-2)",
    },
    statesCount: {
        en: "Count of switched states",
        de: "Anzahl geschaltener States",
        ru: "Количество переключенных состояний",
        pt: "Contagem de estados comutados",
        nl: "Telling van geschakelde staten",
        fr: "Nombre d'états commutés",
        it: "Conteggio degli stati commutati",
        es: "Conteo de estados conmutados",
        pl: "Liczba przełączanych stanów",
        uk: "Кількість переключених станів",
        "zh-cn": "切换状态计数",
    },
    string: {
        en: "string",
        de: "Zeichenkette",
        ru: "строка",
        pt: "corda",
        nl: "draad",
        fr: "chaîne",
        it: "corda",
        es: "cuerda",
        pl: "strunowy",
        uk: "рядок",
        "zh-cn": "串",
    },
    sunrise: {
        en: "Sunrise",
        de: "Sonnenaufgang",
        ru: "Восход",
        pt: "Nascer do sol",
        nl: "zonsopkomst",
        fr: "lever du soleil",
        it: "Alba",
        es: "amanecer",
        pl: "wschód słońca",
        uk: "Схід сонця",
        "zh-cn": "日出",
    },
    sunset: {
        en: "Sunset",
        de: "Sonnenuntergang",
        ru: "Закат солнца",
        pt: "Pôr do sol",
        nl: "Zonsondergang",
        fr: "Le coucher du soleil",
        it: "Tramonto",
        es: "Puesta de sol",
        pl: "Zachód słońca",
        uk: "Захід сонця",
        "zh-cn": "日落",
    },
    switchedType: {
        en: "Switched type",
        de: "Geschaltener Datentyp",
        ru: "Коммутируемый тип",
        pt: "Tipo comutado",
        nl: "Geschakeld type",
        fr: "Type commuté",
        it: "Tipo commutato",
        es: "Tipo conmutado",
        pl: "Typ przełączany",
        uk: "Комутований тип",
        "zh-cn": "切换式",
    },
    switchedValue: {
        en: "Switched value",
        de: "Geschaltener Wert",
        ru: "Переключаемое значение",
        pt: "Valor comutado",
        nl: "Geschakelde waarde",
        fr: "Valeur commutée",
        it: "Valore commutato",
        es: "Valor conmutado",
        pl: "Wartość przełączana",
        uk: "Переключене значення",
        "zh-cn": "切换值",
    },
    "time-switch adapter settings": {
        en: "Adapter settings for time-switch",
        de: "Adaptereinstellungen für time-switch",
        ru: "Настройки адаптера для time-switch",
        pt: "Configurações do adaptador para time-switch",
        nl: "Adapterinstellingen voor time-switch",
        fr: "Paramètres d'adaptateur pour time-switch",
        it: "Impostazioni dell'adattatore per time-switch",
        es: "Ajustes del adaptador para time-switch",
        pl: "Ustawienia adaptera dla time-switch",
        uk: "Налаштування адаптера для таймера",
        "zh-cn": "time-switch的适配器设置",
    },
    trigger: {
        en: "Trigger",
        de: "Auslöser",
        ru: "Вызывать",
        pt: "Desencadear",
        nl: "In gang zetten",
        fr: "Déclencheur",
        it: "grilletto",
        es: "Desencadenar",
        pl: "Wyzwalacz",
        uk: "Тригер",
        "zh-cn": "触发",
    },
    "trigger count": {
        en: "Trigger count",
        de: "Anzahl Auslöser",
        ru: "Количество триггеров",
        pt: "Contagem de gatilhos",
        nl: "Aantal triggers",
        fr: "Nombre de déclencheurs",
        it: "Conteggio dei trigger",
        es: "Recuento de disparadores",
        pl: "Liczba wyzwalaczy",
        uk: "Кількість тригерів",
        "zh-cn": "触发计数",
    },
    true: {
        en: "true",
        de: "ja",
        ru: "правда",
        pt: "verdade",
        nl: "waar",
        fr: "vrai",
        it: "vero",
        es: "cierto",
        pl: "prawdziwe",
        uk: "правда",
        "zh-cn": "真正",
    },
    useAstroIcons: {
        en: "Use astro icons",
        de: "Astro Icons verwenden",
        ru: "Используйте значки Astro",
        pt: "Use ícones astro",
        nl: "Gebruik astropictogrammen",
        fr: "Utiliser des icônes astro",
        it: "Usa le icone astro",
        es: "Usar íconos astro",
        pl: "Użyj ikon astro",
        uk: "Використовуйте астроіконки",
        "zh-cn": "使用astro图标",
    },
    valueType: {
        en: "Value type",
        de: "Werttyp",
        ru: "Тип ценности",
        pt: "Tipo de valor",
        nl: "Waarde type",
        fr: "Type de valeur",
        it: "Tipo di valore",
        es: "Tipo de valor",
        pl: "Typ wartości",
        uk: "Тип значення",
        "zh-cn": "值类型",
    },
    withConstant: {
        en: "With constant",
        de: "Mit Konstante",
        ru: "С постоянным",
        pt: "Com constante",
        nl: "Met constant",
        fr: "Avec constante",
        it: "Con costante",
        es: "Con constante",
        pl: "Ze stałą",
        uk: "З постійним",
        "zh-cn": "不变",
    },
    switch_delay: {
        en: "Delay between 2 switching operations in ms",
        de: "Verzögerung zwischen 2 Schaltvorgängen in ms",
        ru: "Задержка между 2 коммутаторными операциями в мс",
        pt: "Delay entre 2 operações de comutação em ms",
        nl: "Vertraging tussen 2 schakelbewerkingen in ms",
        fr: "Délai entre 2 opérations de commutation en ms",
        it: "Ritardo tra 2 operazioni di commutazione in ms",
        es: "Dilatación entre 2 operaciones de conmutación en ms",
        pl: "Opóźnienie między 2 operacjami przełączania w ms",
        uk: "Прокладання між 2 операціями перемикання в мс",
        "zh-cn": "2个切换操作之间的延迟( ms)",
    },
    addOneTimeTrigger: {
        en: "One time trigger",
        de: "Einmaltrigger",
        ru: "Одноразовый триггер",
        pt: "Gatilho de uma só vez",
        nl: "Eenmalige trigger",
        fr: "Déclencheur unique",
        it: "Innesco una tantum",
        es: "Disparador de una sola vez",
        pl: "Jednorazowy wyzwalacz",
        uk: "Одноразовий тригер",
        "zh-cn": "一次触发",
    },
    oneTimeTriggerInfo: {
        en: "Trigger once in hh:mm:ss:",
        de: "Einmal auslösen in hh:mm:ss:",
        ru: "Один раз запускать в ч: мм: сс:",
        pt: "Acione uma vez em h: mm: ss:",
        nl: "Activeer eenmaal in u:mm:ss:",
        fr: "Déclenchement une fois en h:mm:ss:",
        it: "Attiva una volta in h:mm:ss:",
        es: "Disparo una vez en h: mm: ss:",
        pl: "Aktywuj raz w h:mm:ss:",
        uk: "Тригер один в hh:mm:ss:",
        "zh-cn": "在 h:mm:ss 触发一次：",
    },
};
